name: Matrix
on: push

jobs:
  node-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Log node node-versions
        run: node node-v
      - uses: actions/setup-node@v1
        with:
          node-version: 6
      - name: Log node version
        run: node -v
